[bodystart]
        <script>
          window.MathJax = {
            tex: { tags: 'ams' },
            options: { enableMenu: false },
            startup: { typeset: true }
          };
        </script>
        <script id="MathJax-script" async
          src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
        </script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script>
          function toggle(pId) {
            var e=document.getElementById(pId);
            if (!e) return;
            if (e.style.display == "none") {
              e.style.display = "block"
            } else {
              e.style.display = "none"
            }
            return;
          }
        </script>
</head>
<body>